.TH "shcodecs-enc" 1 "May 2009" "SH Codecs" "Linux-SH Multimedia"

.SH NAME
shcodecs-enc \- Encode V4L2 video input using the SH-Mobile VPU

.SH SYNOPSIS

.B \fBshcodecs-capenc\fR \fIcontrol-file\fR

.SH DESCRIPTION
.B shcodecs-capenc
Encodes V4L2 video input using the SH-Mobile VPU

.SH AUTHORS

shcodecs-enc was written by Conrad Parker

Please report bugs to <linux-sh@vger.kernel.org>
