.TH "shcodecs-record" 1 "June 2009" "SH Codecs" "Linux-SH Multimedia"

.SH NAME
shcodecs-record \- Encode V4L2 video input using the SH-Mobile VPU

.SH SYNOPSIS
.PP
.B \fBshcodecs-record\fR \fIcontrol-file\fR
.PP
.B \fBshcodecs-record\fR [\-r \fBrotate 90\fR | \-\-rotate \fBrotate 90\fR ] [\-i \fBcontrol-file\fR | \-\-input \fBcontrol-file\fR ]
.PP
\fBshcodecs-record\fR [\-h  | \-\-help ]  [\-v  | \-\-version ]

.SH OPTIONS
.PP
\fBshcodecs-record\fR accepts the following options:

.SS "File options"
.IP "\-i \fBcontrol-file\fR, \-\-input \fBcontrol-file\fR" 10
Set the control file.

.SS "Capture options"
.IP "\-r \fBrotate 90\fR, \-\-rotate \fBrotate 90\fR" 10
Rotate and crop the image 90 degrees before encoding.

.SS "Miscellaneous options"
.IP "\-h, \-\-help" 10
Display usage information and exit.
.IP "\-v, \-\-version" 10
Output version information and exit.

.SH DESCRIPTION
.B shcodecs-record
Encodes V4L2 video input using the SH-Mobile VPU

.SH AUTHORS

shcodecs-record was written by Phil Edworthy & Jeremy Baker, based on earlier work by Conrad Parker.

Please report bugs to <linux-sh@vger.kernel.org>
