.TH "shcodecs-enc" 1 "May 2009" "SH Codecs" "Linux-SH Multimedia"

.SH NAME
shcodecs-enc \- Encode a video file using the SH-Mobile VPU

.SH SYNOPSIS

.B \fBshcodecs-enc\fR \fIcontrol-file\fR
.PP
\fBshcodecs-enc\fR [\-h | \-\-help ]  [\-v  | \-\-version ]

.SH OPTIONS
.PP
\fBshcodecs-enc\fR accepts the following options:

.SS "Miscellaneous options"
.IP "\-\-help" 10
Display usage information and exit.
.IP "\-v, \-\-version" 10
Output version information and exit.

.SH DESCRIPTION
.B shcodecs-enc
Encode an input file using the SH-Mobile VPU

.SH AUTHORS

shcodecs-enc was written by Conrad Parker

Please report bugs to <linux-sh@vger.kernel.org>
