.TH "shcodecs-record" 1 "March 2010" "SH Codecs" "Linux-SH Multimedia"

.SH NAME
shcodecs-record \- Encode V4L2 video input using the SH-Mobile VPU

.SH SYNOPSIS
.PP
.B \fBshcodecs-record\fR \fIcontrol-file\fR
.PP
.B \fBshcodecs-record\fR [\-r \fB90\fR | \-\-rotate \fB90\fR ] \fBcontrol-file\fR
.PP
\fBshcodecs-record\fR [\-h  | \-\-help ]  [\-v  | \-\-version ]

.SH OPTIONS
.PP
\fBshcodecs-record\fR accepts the following options:

.SS "File options"
.IP "\fBcontrol-file\fR" 10
Set the control file.

.SS "Capture options"
.IP "\-r \fB90\fR, \-\-rotate \fB90\fR" 10
Rotate and crop the image 90 degrees before encoding.

.SS "Miscellaneous options"
.IP "\-h, \-\-help" 10
Display usage information and exit.
.IP "\-v, \-\-version" 10
Output version information and exit.

.SH DESCRIPTION
.B shcodecs-record
Encodes V4L2 video input as an H.264 or MPEG-4 Elementary Stream using the SH-Mobile VPU.

.SH AUTHORS

shcodecs-record was written by Conrad Parker, Phil Edworthy & Jeremy Baker.

Please report bugs to <linux-sh@vger.kernel.org>
